In [380]:
import pandas as pd
import numpy as np
import json
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.impute import SimpleImputer
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import matplotlib.ticker as mtick
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score, confusion_matrix, precision_score, f1_score, accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [381]:
import os
cwd = os.getcwd()
print(cwd)

C:\Users\Furkan


In [382]:
df = pd.read_csv("indian_liver1.csv")

In [383]:
df

Age  Gender  Total Bilirubin  Direct Bilirubin  Alkaline  Alamine  \
0     65  Female              0.7               0.1       187       16   
1     62    Male             10.9               5.5       699       64   
2     62    Male              7.3               4.1       490       60   
3     58    Male              1.0               0.4       182       14   
4     72    Male              3.9               2.0       195       27   
..   ...     ...              ...               ...       ...      ...   
578   60    Male              0.5               0.1       500       20   
579   40    Male              0.6               0.1        98       35   
580   52    Male              0.8               0.2       245       48   
581   31    Male              1.3               0.5       184       29   
582   38    Male              1.0               0.3       216       21   

     Asparte  Total Proteins  Albumin  Albumin and Globulin Ratio  \
0         18             6.8      3.3                        0.90   
1        100             7.5      3.2                        0.74   
2         68             7.0      3.3                        0.89   
3         20             6.8      3.4                        1.00   
4         59             7.3      2.4                        0.40   
..       ...             ...      ...                         ...   
578       34             5.9      1.6                        0.37   
579       31             6.0      3.2                        1.10   
580       49             6.4      3.2                        1.00   
581       32             6.8      3.4                        1.00   
582       24             7.3      4.4                        1.50   

     Liver or Non Liver  
0                     1  
1                     1  
2                     1  
3                     1  
4                     1  
..                  ...  
578                   2  
579                   1  
580                   1  
581                   1  
582                   2  

[583 rows x 11 columns]

In [384]:
df.dtypes 

Age                             int64
Gender                         object
Total Bilirubin               float64
Direct Bilirubin              float64
Alkaline                        int64
Alamine                         int64
Asparte                         int64
Total Proteins                float64
Albumin                       float64
Albumin and Globulin Ratio    float64
Liver or Non Liver              int64
dtype: object

In [385]:
df.isnull().sum() #eksik veri var mı bakıldı

Age                           0
Gender                        0
Total Bilirubin               0
Direct Bilirubin              0
Alkaline                      0
Alamine                       0
Asparte                       0
Total Proteins                0
Albumin                       0
Albumin and Globulin Ratio    4
Liver or Non Liver            0
dtype: int64

In [386]:
df.head()

Age  Gender  Total Bilirubin  Direct Bilirubin  Alkaline  Alamine  Asparte  \
0   65  Female              0.7               0.1       187       16       18   
1   62    Male             10.9               5.5       699       64      100   
2   62    Male              7.3               4.1       490       60       68   
3   58    Male              1.0               0.4       182       14       20   
4   72    Male              3.9               2.0       195       27       59   

   Total Proteins  Albumin  Albumin and Globulin Ratio  Liver or Non Liver  
0             6.8      3.3                        0.90                   1  
1             7.5      3.2                        0.74                   1  
2             7.0      3.3                        0.89                   1  
3             6.8      3.4                        1.00                   1  
4             7.3      2.4                        0.40                   1

In [387]:
df[np.isnan(df['Albumin and Globulin Ratio'])]  #eksik veri var mı bakıldı

Age  Gender  Total Bilirubin  Direct Bilirubin  Alkaline  Alamine  \
209   45  Female              0.9               0.3       189       23   
241   51    Male              0.8               0.2       230       24   
253   35  Female              0.6               0.2       180       12   
312   27    Male              1.3               0.6       106       25   

     Asparte  Total Proteins  Albumin  Albumin and Globulin Ratio  \
209       33             6.6      3.9                         NaN   
241       46             6.5      3.1                         NaN   
253       15             5.2      2.7                         NaN   
312       54             8.5      4.8                         NaN   

     Liver or Non Liver  
209                   1  
241                   1  
253                   2  
312                   2

In [388]:
df[np.isnan(df['Albumin and Globulin Ratio'])] 
mean_value=df['Albumin and Globulin Ratio'].mean()
mean_value #eksik veriler için ortalama değer bulundu

0.9470639032815201

In [389]:
df['Albumin and Globulin Ratio'].fillna(value=mean_value, inplace=True)  #ortalama değer eksik veri olan sütuna
#yani albumin and globulin ratio kısmına yazıldı

In [390]:
df[np.isnan(df['Albumin and Globulin Ratio'])]

Empty DataFrame
Columns: [Age, Gender, Total Bilirubin, Direct Bilirubin, Alkaline, Alamine, Asparte, Total Proteins, Albumin, Albumin and Globulin Ratio, Liver or Non Liver]
Index: []

In [391]:
df.isnull().sum()

Age                           0
Gender                        0
Total Bilirubin               0
Direct Bilirubin              0
Alkaline                      0
Alamine                       0
Asparte                       0
Total Proteins                0
Albumin                       0
Albumin and Globulin Ratio    0
Liver or Non Liver            0
dtype: int64

In [392]:
df["Gender"]= df["Gender"].map({"Female": 0, "Male": 1}) #cinsiyetler 0 ve 1 olarak isimlendirildi

In [393]:
df.head()

Age  Gender  Total Bilirubin  Direct Bilirubin  Alkaline  Alamine  Asparte  \
0   65       0              0.7               0.1       187       16       18   
1   62       1             10.9               5.5       699       64      100   
2   62       1              7.3               4.1       490       60       68   
3   58       1              1.0               0.4       182       14       20   
4   72       1              3.9               2.0       195       27       59   

   Total Proteins  Albumin  Albumin and Globulin Ratio  Liver or Non Liver  
0             6.8      3.3                        0.90                   1  
1             7.5      3.2                        0.74                   1  
2             7.0      3.3                        0.89                   1  
3             6.8      3.4                        1.00                   1  
4             7.3      2.4                        0.40                   1

In [394]:
df["Liver or Non Liver"]= df["Liver or Non Liver"].map({1: 1, 2: 0})

In [395]:
df2 = df.copy(deep = True) #dataframe'imizi test split kısmında işimize yaraması adına kopyaladık

In [396]:
df2.head()

Age  Gender  Total Bilirubin  Direct Bilirubin  Alkaline  Alamine  Asparte  \
0   65       0              0.7               0.1       187       16       18   
1   62       1             10.9               5.5       699       64      100   
2   62       1              7.3               4.1       490       60       68   
3   58       1              1.0               0.4       182       14       20   
4   72       1              3.9               2.0       195       27       59   

   Total Proteins  Albumin  Albumin and Globulin Ratio  Liver or Non Liver  
0             6.8      3.3                        0.90                   1  
1             7.5      3.2                        0.74                   1  
2             7.0      3.3                        0.89                   1  
3             6.8      3.4                        1.00                   1  
4             7.3      2.4                        0.40                   1

In [397]:
df.head()

Age  Gender  Total Bilirubin  Direct Bilirubin  Alkaline  Alamine  Asparte  \
0   65       0              0.7               0.1       187       16       18   
1   62       1             10.9               5.5       699       64      100   
2   62       1              7.3               4.1       490       60       68   
3   58       1              1.0               0.4       182       14       20   
4   72       1              3.9               2.0       195       27       59   

   Total Proteins  Albumin  Albumin and Globulin Ratio  Liver or Non Liver  
0             6.8      3.3                        0.90                   1  
1             7.5      3.2                        0.74                   1  
2             7.0      3.3                        0.89                   1  
3             6.8      3.4                        1.00                   1  
4             7.3      2.4                        0.40                   1

In [398]:
df2.drop('Age', axis=1, inplace=True)
df2.drop('Gender', axis=1, inplace=True)
df2.drop('Total Bilirubin', axis=1, inplace=True)
df2.drop('Direct Bilirubin', axis=1, inplace=True)
df2.drop('Alkaline', axis=1, inplace=True)
df2.drop('Alamine', axis=1, inplace=True)
df2.drop('Asparte', axis=1, inplace=True)
df2.drop('Total Proteins', axis=1, inplace=True)
df2.drop('Albumin', axis=1, inplace=True)
df2.drop('Albumin and Globulin Ratio', axis=1, inplace=True)
df.drop('Liver or Non Liver', axis=1, inplace=True)
df #df2 dataframe'imizde sadece 1 sütun yani liver or non liver değeri bırakıldı, df dataframe'imizde ise 
#o sütun hariç hepsi bırakıldı

Age  Gender  Total Bilirubin  Direct Bilirubin  Alkaline  Alamine  \
0     65       0              0.7               0.1       187       16   
1     62       1             10.9               5.5       699       64   
2     62       1              7.3               4.1       490       60   
3     58       1              1.0               0.4       182       14   
4     72       1              3.9               2.0       195       27   
..   ...     ...              ...               ...       ...      ...   
578   60       1              0.5               0.1       500       20   
579   40       1              0.6               0.1        98       35   
580   52       1              0.8               0.2       245       48   
581   31       1              1.3               0.5       184       29   
582   38       1              1.0               0.3       216       21   

     Asparte  Total Proteins  Albumin  Albumin and Globulin Ratio  
0         18             6.8      3.3                        0.90  
1        100             7.5      3.2                        0.74  
2         68             7.0      3.3                        0.89  
3         20             6.8      3.4                        1.00  
4         59             7.3      2.4                        0.40  
..       ...             ...      ...                         ...  
578       34             5.9      1.6                        0.37  
579       31             6.0      3.2                        1.10  
580       49             6.4      3.2                        1.00  
581       32             6.8      3.4                        1.00  
582       24             7.3      4.4                        1.50  

[583 rows x 10 columns]

In [399]:
df2

Liver or Non Liver
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
578                   0
579                   1
580                   1
581                   1
582                   0

[583 rows x 1 columns]

In [400]:
x = df.values
x

array([[65.  ,  0.  ,  0.7 , ...,  6.8 ,  3.3 ,  0.9 ],
       [62.  ,  1.  , 10.9 , ...,  7.5 ,  3.2 ,  0.74],
       [62.  ,  1.  ,  7.3 , ...,  7.  ,  3.3 ,  0.89],
       ...,
       [52.  ,  1.  ,  0.8 , ...,  6.4 ,  3.2 ,  1.  ],
       [31.  ,  1.  ,  1.3 , ...,  6.8 ,  3.4 ,  1.  ],
       [38.  ,  1.  ,  1.  , ...,  7.3 ,  4.4 ,  1.5 ]])

In [401]:
y = df2.values
y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [402]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0) #veri test splite sokuldu
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [403]:
knn_model = KNeighborsClassifier(n_neighbors = 11) 
knn_model.fit(x_train,np.ravel(y_train)) #KNN İÇİN GEREKEN KULLANILACAK KOMŞU SAYISI 11 OLARAK BELİRLENDİ.
predicted_y = knn_model.predict(x_test)
accuracy_knn = knn_model.score(x_test,y_test)#TAHMİN EDİLEN PREDICTED Y DEĞERİ X_TEST İLE GÖSTERİLDİ
print("KNN accuracy:",accuracy_knn)#ACCURACY BELİRLENMESİ İÇİN X_TEST VE Y_TEST KULLANILDI

KNN accuracy: 0.6438356164383562


In [404]:
print(classification_report(y_test, predicted_y))

              precision    recall  f1-score   support

           0       0.36      0.17      0.24        46
           1       0.69      0.86      0.77       100

    accuracy                           0.64       146
   macro avg       0.53      0.52      0.50       146
weighted avg       0.59      0.64      0.60       146



In [405]:
logr = LogisticRegression(random_state=0)
logr.fit(x_train,np.ravel(y_train))
y_pred = logr.predict(x_test)
confusion_matrix(y_test,y_pred)

array([[ 8, 38],
       [ 7, 93]], dtype=int64)

In [406]:
accuracy_knn = logr.score(x_test,y_test)
print("Logistic Regression accuracy:",accuracy_knn)
#MODEL LOGISTIC REGRESSION ILE DE DENENDİ

Logistic Regression accuracy: 0.6917808219178082


In [407]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.53      0.17      0.26        46
           1       0.71      0.93      0.81       100

    accuracy                           0.69       146
   macro avg       0.62      0.55      0.53       146
weighted avg       0.65      0.69      0.63       146



In [408]:
dtc = DecisionTreeClassifier(criterion = "entropy")
dtc.fit(x_train,np.ravel(y_train))
y_pred = dtc.predict(x_test)
cm=confusion_matrix(y_test,y_pred) #MODEL KARAR AĞACI İLE DENENDİ
print("Decision Tree")
print(cm)

Decision Tree
[[23 23]
 [21 79]]


In [409]:
rfc = RandomForestClassifier(n_estimators = 10,criterion = 'entropy')
rfc.fit(x_train,np.ravel(y_train))
y_pred = rfc.predict(x_test)
cm = confusion_matrix(y_test,y_pred) #MODEL RASSAL ORMAN İLE DE DENENDİ.
print('Random Forest')
print(cm)

Random Forest
[[15 31]
 [18 82]]
